-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 17:02:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario` DEFAULT CHARACTER SET utf8 ;
USE `concesionario` ;

-- -----------------------------------------------------
-- Table `concesionario`.`fabricantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concesionario`.`fabricantes` ;

CREATE TABLE IF NOT EXISTS `concesionario`.`fabricantes` (
  `id_fabricantes` INT NOT NULL AUTO_INCREMENT,
  `nombre_fabricante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fabricantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`coches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concesionario`.`coches` ;

CREATE TABLE IF NOT EXISTS `concesionario`.`coches` (
  `id_coches` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(20) NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  `anio` INT NOT NULL,
  `id_fabricantes` INT NOT NULL,
  PRIMARY KEY (`id_coches`),
  UNIQUE INDEX `id_coches_UNIQUE` (`id_coches` ASC) ,
  INDEX `fk_coches_fabricantes_idx` (`id_fabricantes` ASC) ,
  CONSTRAINT `fk_coches_fabricantes`
    FOREIGN KEY (`id_fabricantes`)
    REFERENCES `concesionario`.`fabricantes` (`id_fabricantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
