-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 10:12:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS empresa_papeleria;
CREATE DATABASE empresa_papeleria;
USE empresa_papeleria;

DROP TABLE IF EXISTS `empresa_papeleria`.`empresas` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(45) NOT NULL,
  `cif_empresa` VARCHAR(9) NOT NULL,
  `pais_empresa` VARCHAR(20) NOT NULL,
  `direccion_empresa` VARCHAR(45) NOT NULL,
  `codigo_postal_empresa` INT NOT NULL,
  `es_admin` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC) ,
  UNIQUE INDEX `cif_empresa_UNIQUE` (`cif_empresa` ASC) ,
  UNIQUE INDEX `razon_social_UNIQUE` (`razon_social` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`carrito` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`carrito` (
  `id_carrito` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_carrito`),
  UNIQUE INDEX `id_carrito_UNIQUE` (`id_carrito` ASC) ,
  INDEX `fk_carrito_empresas1_idx` (`id_empresa` ASC) ,
  CONSTRAINT `fk_carrito_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresa_papeleria`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `estado_de_envio` VARCHAR(2) NOT NULL,
  `cuenta_de_pago` VARCHAR(45) NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `id_producto` INT NOT NULL,
  `carrito_id_carrito` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC) ,
  INDEX `fk_pedidos_carrito1_idx` (`carrito_id_carrito` ASC) ,
  CONSTRAINT `fk_pedidos_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `empresa_papeleria`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`categorias` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`categorias` (
  `id_categorias` INT NOT NULL,
  `tipo_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categorias`),
  UNIQUE INDEX `id_categorias_UNIQUE` (`id_categorias` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`productos` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion_producto` VARCHAR(45) NOT NULL,
  `peso_producto` VARCHAR(45) NULL,
  `tamanio_producto` VARCHAR(45) NULL,
  `imagen_producto` LONGBLOB NOT NULL,
  `id_categorias` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC) ,
  INDEX `fk_productos_categorias1_idx` (`id_categorias` ASC) ,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`id_categorias`)
    REFERENCES `empresa_papeleria`.`categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`credenciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`credenciales` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`credenciales` (
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(16) NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`correo`),
  INDEX `fk_credenciales_empresas1_idx` (`id_empresa` ASC) ,
  CONSTRAINT `fk_credenciales_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresa_papeleria`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`detalle_carrito` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`detalle_carrito` (
  `id_producto` INT NOT NULL,
  `id_carrito` INT NOT NULL,
  `cantidad_producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_carrito`),
  INDEX `fk_productos_has_carrito_carrito1_idx` (`id_carrito` ASC) ,
  INDEX `fk_productos_has_carrito_productos1_idx` (`id_producto` ASC) ,
  CONSTRAINT `fk_productos_has_carrito_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `empresa_papeleria`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_carrito_carrito1`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `empresa_papeleria`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_papeleria`.`usuario_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_papeleria`.`usuario_admin` ;

CREATE TABLE IF NOT EXISTS `empresa_papeleria`.`usuario_admin` (
  `id_usuario_admin` INT NOT NULL AUTO_INCREMENT,
  `correo_admin` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(16) NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_usuario_admin`),
  INDEX `fk_usuario_admin_empresas1_idx` (`id_empresa` ASC) ,
  CONSTRAINT `fk_usuario_admin_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `empresa_papeleria`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
